import {
  boolean,
  integer,
  jsonb,
  pgTable,
  real,
  serial,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";

/** Data Hub sources — live connections or snapshot feeds */
export const dataSources = pgTable("data_sources", {
  id: serial("id").primaryKey(),
  slug: varchar("slug", { length: 120 }).notNull().unique(),
  name: varchar("name", { length: 200 }).notNull(),
  kind: varchar("kind", { length: 80 }).notNull(), // log | metric | trace | event | external
  provider: varchar("provider", { length: 160 }).notNull(),
  endpoint: text("endpoint").notNull(),
  status: varchar("status", { length: 40 }).notNull().default("connected"),
  lastIngestAt: timestamp("last_ingest_at", { withTimezone: true }).defaultNow(),
  eventsToday: integer("events_today").notNull().default(0),
  tags: jsonb("tags").$type<string[]>().notNull().default([]),
});

/** Insights generated by automated analysis */
export const insights = pgTable("insights", {
  id: serial("id").primaryKey(),
  kind: varchar("kind", { length: 60 }).notNull(), // anomaly | correlation | risk_shift | gap
  title: varchar("title", { length: 240 }).notNull(),
  summary: text("summary").notNull(),
  evidence: text("evidence").notNull(),
  severity: varchar("severity", { length: 20 }).notNull(),
  sources: jsonb("sources").$type<string[]>().notNull().default([]),
  status: varchar("status", { length: 40 }).notNull().default("open"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});
